# Generated by Django 4.2.7 on 2023-11-21 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_catalyst_count', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='Password',
            field=models.CharField(default='123', max_length=50),
        ),
    ]
